### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by expede** [fission-suite/fission-codes-web#4]
It says `Fiunancial` in these places 🤦‍♀️

* https://github.com/fission-suite/fission-codes-web/blob/2a3cf0fd50a1a6072df90290cd4bd7516ef899d7/fission-codes/codes.md#L179
* https://github.com/fission-suite/fission-codes-web/blob/2a3cf0fd50a1a6072df90290cd4bd7516ef899d7/fission-codes/grid.md#L25
* https://github.com/fission-suite/fission-codes-web/blob/2a3cf0fd50a1a6072df90290cd4bd7516ef899d7/fission-codes/erc1066.md#L251
* https://github.com/fission-suite/fission-codes-web/blob/2a3cf0fd50a1a6072df90290cd4bd7516ef899d7/fission-codes/erc1066.md#L373

**Comment by bmann** [comment]
Done!
